CREATE SCHEMA IF NOT EXISTS recipients AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS sources AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS notifications AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS delivery AUTHORIZATION CURRENT_USER;
